version: '3.9'

services:
  zookeeper:
    container_name: cdc_zookeeper
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    restart: always
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  kafka:
    container_name: cdc_kafka
    image: debezium/kafka:${DEBEZIUM_VERSION}
    restart: always
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181

  postgres:
    container_name: cdc_postgres
    build: ./postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgadmin

  connect:
    container_name: cdc_connect
    build:
      context: ./debezium-connect
      args:
        - DEBEZIUM_VERSION=${DEBEZIUM_VERSION}
    ports:
      - "8083:8083"
    links:
      - kafka
      - postgres
      - elasticsearch
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses

  elasticsearch:
    container_name: cdc_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.22
    restart: always
    ports:
      - "9200:9200"
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"